const Icons = {
  area: `${process.env.PUBLIC_URL}/images/icons/area.svg`,
  bed: `${process.env.PUBLIC_URL}/images/icons/bed.svg`,
  bath: `${process.env.PUBLIC_URL}/images/icons/bx_bath.svg`,
  customerService: `${process.env.PUBLIC_URL}/images/icons/customer-service.svg`,
  down: `${process.env.PUBLIC_URL}/images/icons/down.svg`,
  facebook: `${process.env.PUBLIC_URL}/images/icons/facebook.svg`,
  copy: `${process.env.PUBLIC_URL}/images/icons/fi_copy.svg`,
  home2: `${process.env.PUBLIC_URL}/images/icons/fi_home (2).svg`,
  home: `${process.env.PUBLIC_URL}/images/icons/fi_home.svg`,
  info: `${process.env.PUBLIC_URL}/images/icons/fi_info.svg`,
  list: `${process.env.PUBLIC_URL}/images/icons/fi_list.svg`,
  mapPin: `${process.env.PUBLIC_URL}/images/icons/fi_map-pin.svg`,
  cameraPin: `${process.env.PUBLIC_URL}/images/icons/fi_camera.svg`,
  share2: `${process.env.PUBLIC_URL}/images/icons/fi_share-2.svg`,
  fillHeart: `${process.env.PUBLIC_URL}/images/icons/Fill Heart.svg`,
  send: `${process.env.PUBLIC_URL}/images/icons/icon-send.svg`,
  instagram: `${process.env.PUBLIC_URL}/images/icons/instagram.svg`,
  langs: `${process.env.PUBLIC_URL}/images/icons/langs.svg`,
  like: `${process.env.PUBLIC_URL}/images/icons/like.svg`,
  liked: `${process.env.PUBLIC_URL}/images/icons/liked.svg`,
  lines: `${process.env.PUBLIC_URL}/images/icons/lines.svg`,
  linkedin: `${process.env.PUBLIC_URL}/images/icons/linkedin.svg`,
  location: `${process.env.PUBLIC_URL}/images/icons/Location.svg`,
  logo: `${process.env.PUBLIC_URL}/images/icons/logo.svg`,
  owners: `${process.env.PUBLIC_URL}/images/icons/owners.svg`,
  payment: `${process.env.PUBLIC_URL}/images/icons/payment.svg`,
  renting: `${process.env.PUBLIC_URL}/images/icons/Renting.svg`,
  rightYellow: `${process.env.PUBLIC_URL}/images/icons/right-yellow.svg`,
  right: `${process.env.PUBLIC_URL}/images/icons/right.svg`,
  searchIcon: `${process.env.PUBLIC_URL}/images/icons/searchIcon.svg`,
  star: `${process.env.PUBLIC_URL}/images/icons/star.svg`,
  timeCircle: `${process.env.PUBLIC_URL}/images/icons/Time Circle.svg`,
  twitter: `${process.env.PUBLIC_URL}/images/icons/twitter.svg`,
  whiteRight: `${process.env.PUBLIC_URL}/images/icons/white-right.svg`,
  Loader: `${process.env.PUBLIC_URL}/images/icons/fi_loader.svg`,
  error: `${process.env.PUBLIC_URL}/images/icons/404.svg`,
  up: `${process.env.PUBLIC_URL}/images/icons/up-arrow.svg`,
  "down-yellow": `${process.env.PUBLIC_URL}/images/icons/Drop-Down-yellow.svg`,
  filter: `${process.env.PUBLIC_URL}/images/icons/Filter 24px.svg`,
  starEmpty: `${process.env.PUBLIC_URL}/images/icons/Star-empty.svg`,
  Resturants: `${process.env.PUBLIC_URL}/images/icons/food-outline.svg`,
  Transportation: `${process.env.PUBLIC_URL}/images/icons/transportation.svg`,
  rightArrow: `${process.env.PUBLIC_URL}/images/icons/fi_arrow-right.svg`,
  rightArrowGrey: `${process.env.PUBLIC_URL}/images/icons/right_grey.svg`,
  leftArrow: `${process.env.PUBLIC_URL}/images/icons/fi_arrow-left.svg`,
  leftArrowBlue: `${process.env.PUBLIC_URL}/images/icons/fi_arrow-left_blue.svg`,
  leftArrowWhite: `${process.env.PUBLIC_URL}/images/icons/fi_arrow-left-white.svg`,
  leftArrowGrey: `${process.env.PUBLIC_URL}/images/icons/fi_arrow-left_grey.svg`,
  leftArrowYellow: `${process.env.PUBLIC_URL}/images/icons/fi_arrow-left_Yellow.svg`,
  X: `${process.env.PUBLIC_URL}/images/icons/fi_x.svg`,
  X_blue: `${process.env.PUBLIC_URL}/images/icons/fi_x_blue.svg`,
  chevronDown: `${process.env.PUBLIC_URL}/images/icons/fi_chevron-down.svg`,
  Date: `${process.env.PUBLIC_URL}/images/icons/date.svg`,
  Time: `${process.env.PUBLIC_URL}/images/icons/time.svg`,
  WhiteArrowRight: `${process.env.PUBLIC_URL}/images/icons/fi_arrow-right-white.svg`,
  arrowRight: `${process.env.PUBLIC_URL}/images/icons/Arrow - Down 2.svg`,
  eyeClosed: `${process.env.PUBLIC_URL}/images/icons/hide.svg`,
  eyeOpen: `${process.env.PUBLIC_URL}/images/icons/hide_blue.svg`,
  phone: `${process.env.PUBLIC_URL}/images/icons/fi_phone-call.svg`,
  whatsApp: `${process.env.PUBLIC_URL}/images/icons/what's.svg`,
  emailBordered: `${process.env.PUBLIC_URL}/images/icons/email-bordered.svg`,
  phoneBordered: `${process.env.PUBLIC_URL}/images/icons/phone-bordered.svg`,
  mapBordered: `${process.env.PUBLIC_URL}/images/icons/map-bordered.svg`,
  timeBordered: `${process.env.PUBLIC_URL}/images/icons/time-bordered.svg`,
  searchBlack: `${process.env.PUBLIC_URL}/images/icons/search-black.svg`,
  filterBlack: `${process.env.PUBLIC_URL}/images/icons/filter-black.svg`,
  send: `${process.env.PUBLIC_URL}/images/icons/send.svg`,
  quote: `${process.env.PUBLIC_URL}/images/icons/bi_quote.svg`,
  doubleArrowLeftBlack: `${process.env.PUBLIC_URL}/images/icons/doubleArrow.svg`,
  image: `${process.env.PUBLIC_URL}/images/icons/img.svg`,
  cameraBlue: `${process.env.PUBLIC_URL}/images/icons/camera.svg`,
  doubleArrowRightWhite: `${process.env.PUBLIC_URL}/images/icons/double_arrows_right.svg`,
  googlePlay: `${process.env.PUBLIC_URL}/images/icons/googlePlay.svg`,
  visa: `${process.env.PUBLIC_URL}/images/icons/visa.svg`,
  paypal: `${process.env.PUBLIC_URL}/images/icons/paypal.svg`,
  paypass: `${process.env.PUBLIC_URL}/images/icons/paypass.svg`,
  video: `${process.env.PUBLIC_URL}/images/icons/video.svg`,
  dashboard: `${process.env.PUBLIC_URL}/images/icons/dashboard.svg`,
  bookings: `${process.env.PUBLIC_URL}/images/icons/bookings.svg`,
  requests: `${process.env.PUBLIC_URL}/images/icons/requests.svg`,
  wishlist: `${process.env.PUBLIC_URL}/images/icons/wishlist.svg`,
  myProfile: `${process.env.PUBLIC_URL}/images/icons/myProfile.svg`,
  logOut: `${process.env.PUBLIC_URL}/images/icons/logOut.svg`,
  eye: `${process.env.PUBLIC_URL}/images/icons/eye.svg`,
  delete: `${process.env.PUBLIC_URL}/images/icons/delete.svg`,
  pen: `${process.env.PUBLIC_URL}/images/icons/pen.svg`,
  dashboardHome: `${process.env.PUBLIC_URL}/images/icons/home.svg`,
  payments: `${process.env.PUBLIC_URL}/images/icons/payments.svg`,
};

export default Icons;
